defmodule AtmlPdfTest do
  @moduledoc false
  use ExUnit.Case
  doctest AtmlPdf
  doctest AtmlPdf.Renderer

  # ---------------------------------------------------------------------------
  # End-to-end: render_binary/2 on the full spec example
  # ---------------------------------------------------------------------------

  @full_example_xml """
  <document width="400pt" height="600pt" font-family="Helvetica" font-size="8pt">
    <row height="60pt" border-bottom="solid 1pt #000000">
      <col width="80pt" vertical-align="center" text-align="center" padding="4pt">
      </col>
      <col width="fill" vertical-align="center" padding="4pt 8pt"
           font-size="14pt" font-weight="bold" text-align="center">
        AIR WAYBILL
      </col>
    </row>
    <row height="fill" border-bottom="solid 1pt #000000">
      <col width="50%" padding="6pt" border-right="solid 1pt #000000">
        <row height="fit">
          <col font-weight="bold" font-size="7pt">SENDER</col>
        </row>
        <row height="fill">
          <col padding-top="4pt">John Doe, 123 Street, Ho Chi Minh City</col>
        </row>
      </col>
      <col width="fill" padding="6pt">
        <row height="fit">
          <col font-weight="bold" font-size="7pt">RECIPIENT</col>
        </row>
        <row height="fill">
          <col padding-top="4pt">Jane Smith, 456 Avenue, Hanoi</col>
        </row>
      </col>
    </row>
    <row height="40pt" border-bottom="solid 1pt #000000">
      <col width="33%" padding="4pt 6pt" border-right="solid 1pt #000000">
        <row height="fit">
          <col font-weight="bold" font-size="7pt">WEIGHT</col>
        </row>
        <row height="fill">
          <col vertical-align="center">2.5 kg</col>
        </row>
      </col>
      <col width="33%" padding="4pt 6pt" border-right="solid 1pt #000000">
        <row height="fit">
          <col font-weight="bold" font-size="7pt">DIMENSIONS</col>
        </row>
        <row height="fill">
          <col vertical-align="center">30 x 20 x 15 cm</col>
        </row>
      </col>
      <col width="fill" padding="4pt 6pt">
        <row height="fit">
          <col font-weight="bold" font-size="7pt">SERVICE</col>
        </row>
        <row height="fill">
          <col vertical-align="center">Express</col>
        </row>
      </col>
    </row>
    <row height="28pt">
      <col text-align="center" vertical-align="center"
           font-size="11pt" font-weight="bold">
        VN-123456789-SG
      </col>
    </row>
  </document>
  """

  describe "render_binary/2" do
    test "returns {:ok, binary} for the full spec example" do
      assert {:ok, binary} = AtmlPdf.render_binary(@full_example_xml)
      assert is_binary(binary)
      assert byte_size(binary) > 0
    end

    test "produced binary starts with PDF header" do
      {:ok, binary} = AtmlPdf.render_binary(@full_example_xml)
      assert binary =~ "%PDF-"
    end

    test "returns {:ok, binary} for a minimal document" do
      xml = ~s|<document width="100pt" height="100pt"></document>|
      assert {:ok, binary} = AtmlPdf.render_binary(xml)
      assert byte_size(binary) > 0
    end

    test "returns {:error, _} for malformed XML" do
      assert {:error, _} = AtmlPdf.render_binary("<not valid xml")
    end
  end

  describe "render/3" do
    test "writes a PDF file to disk for the full spec example" do
      path =
        Path.join(System.tmp_dir!(), "atml_e2e_test_#{:erlang.unique_integer([:positive])}.pdf")

      try do
        assert :ok = AtmlPdf.render(@full_example_xml, path)
        assert File.exists?(path)
        assert File.stat!(path).size > 0
      after
        File.rm(path)
      end
    end
  end

  # ---------------------------------------------------------------------------
  # End-to-end: document with image and barcode generated by Barlix
  # ---------------------------------------------------------------------------

  # Generates a PNG barcode for `value` using Barlix.Code128 and returns
  # a base64-encoded string suitable for an ATML <img src="base64:..."> attr.
  defp barcode_base64(value, opts) do
    {:ok, iodata} =
      value
      |> Barlix.Code128.encode!()
      |> Barlix.PNG.print(opts)

    iodata |> IO.iodata_to_binary() |> Base.encode64()
  end

  # Generates a minimal 1×1 white PNG binary (smallest valid PNG).
  defp tiny_png_base64 do
    # 1×1 white pixel PNG, standard header + IHDR + IDAT + IEND
    Base.encode64(
      <<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8,
        2, 0, 0, 0, 144, 119, 83, 222, 0, 0, 0, 12, 73, 68, 65, 84, 8, 215, 99, 248, 207, 192, 0,
        0, 0, 2, 0, 1, 226, 33, 188, 51, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130>>
    )
  end

  describe "render_binary/2 with image and barcode" do
    test "generates a full PDF containing a base64 PNG image and a barlix barcode" do
      barcode_b64 = barcode_base64("VN-123456789-SG", xdim: 2, height: 40, margin: 4)
      image_b64 = tiny_png_base64()

      xml = """
      <document width="400pt" height="600pt" font-family="Helvetica" font-size="8pt">
        <row height="60pt" border-bottom="solid 1pt #000000">
          <col width="fill" vertical-align="center" text-align="center"
               font-size="14pt" font-weight="bold">
            AIR WAYBILL
          </col>
        </row>
        <row height="80pt" border-bottom="solid 1pt #000000">
          <col width="fill" vertical-align="center" text-align="center" padding="4pt">
            <img src="base64:#{image_b64}" width="60pt" height="60pt" />
          </col>
        </row>
        <row height="fill" border-bottom="solid 1pt #000000">
          <col width="50%" padding="6pt" border-right="solid 1pt #000000">
            <row height="fit">
              <col font-weight="bold" font-size="7pt">SENDER</col>
            </row>
            <row height="fill">
              <col padding-top="4pt">John Doe, 123 Street, Ho Chi Minh City</col>
            </row>
          </col>
          <col width="fill" padding="6pt">
            <row height="fit">
              <col font-weight="bold" font-size="7pt">RECIPIENT</col>
            </row>
            <row height="fill">
              <col padding-top="4pt">Jane Smith, 456 Avenue, Hanoi</col>
            </row>
          </col>
        </row>
        <row height="60pt" border-bottom="solid 1pt #000000">
          <col width="fill" vertical-align="center" text-align="center" padding="4pt">
            <img src="base64:#{barcode_b64}" width="300pt" height="40pt" />
          </col>
        </row>
        <row height="28pt">
          <col text-align="center" vertical-align="center"
               font-size="11pt" font-weight="bold">
            VN-123456789-SG
          </col>
        </row>
      </document>
      """

      assert {:ok, binary} = AtmlPdf.render_binary(xml)
      assert is_binary(binary)
      assert byte_size(binary) > 0
      assert binary =~ "%PDF-"
    end

    test "writes PDF with image and barcode to disk" do
      barcode_b64 = barcode_base64("VN-TRACK-001", xdim: 2, height: 50, margin: 6)
      image_b64 = tiny_png_base64()

      xml = """
      <document width="400pt" height="300pt" font-family="Helvetica" font-size="8pt">
        <row height="80pt" border-bottom="solid 1pt #000000">
          <col width="fill" vertical-align="center" text-align="center" padding="4pt">
            <img src="base64:#{image_b64}" width="60pt" height="60pt" />
          </col>
        </row>
        <row height="70pt" border-bottom="solid 1pt #000000">
          <col width="fill" vertical-align="center" text-align="center" padding="4pt">
            <img src="base64:#{barcode_b64}" width="320pt" height="50pt" />
          </col>
        </row>
        <row height="fill">
          <col text-align="center" vertical-align="center" font-weight="bold">
            VN-TRACK-001
          </col>
        </row>
      </document>
      """

      path =
        Path.join(
          System.tmp_dir!(),
          "atml_barcode_test_#{:erlang.unique_integer([:positive])}.pdf"
        )

      try do
        assert :ok = AtmlPdf.render(xml, path)
        assert File.exists?(path)
        assert File.stat!(path).size > 0
      after
        File.rm(path)
      end
    end
  end
end
